---

- name: Update APT Machines
  hosts: apt
  roles:
    - role: roles/apt/
  
- name: Update Flatpak Machines
  hosts: flatpak
  roles:
    - role: roles/flatpak/

- name: Update DNS Server
  hosts: adguard
  roles:
    - role: roles/adguard/