---

- name: Ensure existence of ADGuard working directory
  file:
    path: "{{ work_dir }}"
    state: directory
  become: true

- name: Ensure existence of ADGuard config directory
  file:
    path: "{{ conf_dir }}"
    state: directory
  become: true

- name: Ensure AdGuard Server is running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: adguard/adguardhome
    state: present
    restart: "{{ restart_policy }}"
    network_mode: host
    mounts:
      - source: "{{ work_dir }}"
        target: /opt/adguardhome/work
        read_only: no
        type: bind
      - source: "{{ conf_dir }}"
        target: /opt/adguardhome/conf
        read_only: no
        type: bind
    exposed_ports:
      - "53"
      - "53/udp"
      - "80"
      - "443"
      - "443/udp"
      - "3000"
      
- name: Ensure adguard service exists
  template:
    src: adguard.unit.j2
    dest: /etc/systemd/system/adguard.service
  become: true

- name: Reload systemd daemon
  systemd:
    name: daemon-reload
  become: true

- name: Start and enable AdGuard service
  systemd:
    name: adguard
    enabled: yes
  become: true