---

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true

- name: Ensure existence of ADGuard working directory
  file:
    path: /opt/adguardhome/work
    state: directory
  become: true

- name: Ensure existence of ADGuard config directory
  file:
    path: /opt/adguardhome/conf
    state: directory
  become: true

- name: Ensure AdGuard Server is running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: adguard/adguardhome
    state: present
    restart: "{{ restart_policy }}"
    network_mode: host
    mounts:
      - source: "/opt/adguardhome/work"
        target: /opt/adguardhome/work
        read_only: no
        type: bind
      - source: "/opt/adguardhome/conf"
        target: /opt/adguardhome/conf
        read_only: no
        type: bind
    exposed_ports:
      - "53"
      - "53/udp"
      - "80"
      - "443"
      - "443/udp"
      - "3000"
      
