---

- name: Ensure fail2ban installed
  apt:
    name: fail2ban
    state: present
      
- name: Ensure fail2ban config exists
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  become: true

- name: Ensure fail2ban started
  systemd:
    name: "fail2ban"
    state: started
    enabled: yes