---

- name: Upgrade all flatpaks 📅
  ansible.builtin.command: flatpak update --noninteractive
  register: flatpak_update_output
  changed_when: "'app/' in flatpak_update_output.stdout"

- name: Add the flathub flatpak repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system