---

- name: Back up existing igntion
  copy: 
    src: /www/ignition/nas.ign
    dest: /www/ignition/nas.ign.old
    remote_src: yes

- name: Fetch new ignition file
  copy: 
    src: /tmp/nas.ign
    dest: /www/ignition/nas.ign
  
