---

- name: Build Igntion file for CoreOS Server
  hosts: build_server
  roles:
    - roles/workstation/

- name: Update Igntion file on PXE Server
  hosts: router
  roles:
    - roles/router/

- name: Restart homelab
  hosts: homelab
  roles:
    - roles/homelab/