---

- name: Update APT Machines
  hosts: apt
  roles:
    - role: roles/apt/
  
- name: Update Flatpak Machines
  hosts: flatpak
  roles:
    - role: roles/flatpak/

- name: Update Hardening
  hosts: hardened
  roles:
    - role: roles/hardened/

- name: Update DynDNS Service
  hosts: dyndns
  roles:
    - role: roles/dyndns/
